version: "3"
services:
    database:
        image: "postgres:10.5"
        container_name: "postgresql-database"
        ports:
            - "5432:5432"
        volumes:
            - ./db-init-sql/init-pg-database.sql:/docker-entrypoint-initdb.d/init.sql
